language: node_js
node_js:
- '6'
install:
- npm install
branches:
  only:
  - master
before_script:
- npm run lint
before_deploy:
- npm run build
deploy:
- provider: heroku
  api_key:
    secure: pGnrJ92lrvHyIvhJN0Lnw/UVnenrLkied7krwq40tr66+NZG0CFbzsYhrT1/4iqrbcYeSkB221A8C2j6XuIAKpY1ItNkbPOOd74jbVpf6NW40RMq/yylQd3iyxIYFA+khYkF53sGv7Z2hYeZbDCOsXCrvDIT+PbYc4TpEJ7SZgJai7E0S6pDUj+abnxUHugULOF+T8hV/X4kTdgA/EkkqvDXZiuO4GUeClXpjeCHObv+4jJl53MZJqnkze6oxFLAl55Rgpxozcyq8WBrxqp9tNGWPzevNFK1qu4o6LxlAPZ1BZP1Y42HCZe7jrTSj0rBPH3sXuwJ7/V7NyUUK7UnwMSivjNB8cYPRiR/RphP4oljWuHk8iwCzmxhEUFQFrJFMi4ZeYb0BxUKXekDZckY2Rsl6zX+l2A0P2gfErOhykvMWIlrDRBxoAlp20DviK3k0rGrJ7VcwU7vpJwY8TZzY8Dqpdn31NOctyBnQ95MF8bLzWmJ+3H3uEquYoxdYToc20lVBjdS6he4qzTgh3pT03Jg4lUEkJc7kSX8zm+UsbJJmqEDC2JrSRX9b11syOQkyjLGBaV3aP953YN4DsMG6EDdealFs9zCrWkLnbMhncecdpsBVESO39dMIPNW6cv+u5UHM1/l9wYY6e3WC7s1ar4RerQ4rmCEVq3m5Wa2x+I=
  app: super-photo-quest
  on:
    repo: urfu-2016/team4
- provider: surge
  project: "./build/public/"
  domain: super-photo-quest.surge.sh
  skip_cleanup: true
  SURGE_LOGIN: team4hackaton@scryptmail.com
  SURGE_TOKEN:
    secure: P5vF2kBTNb/0cYl5ULHyg+M36KusLPhuJcDnZJSserAn8sFjmv60cIDrMYdp7ncvtqgWp+tXZQ0ixcH5zDHWsMeV+qjqQEqUsf+LePRea91jqEbMvRsg+7G1vIrgwmuIEsARq5ZrGbjwJ2yN7WVec5VxLSZIpwpZYxK+catyEKCpcPlIjVjGHmYjYlzpns353GSV90EBAKc+8524EvZUQIQUE4ZET6fr0eXdobnfZPHwkzwUxQoUAtTToNz0s/yK3doWkMNSCgLE3pVFoGhcZnElAIr1dR6aU2tqZL2qPDjvQ21YiCe71oCmI/7Y+WkVgfU7G7YY2pyzUCtjjeOkuu/tHI1AdoWyuHMB1HwjYEh21j5RuvtYesKbZHb//M/7UbSWcVeEeLeEofvsKrYuy8jBZnzc9XaUkwM5XOq9lTCCNO4zfluaU83iDrU6plMHE3P9q94Odnm4hM97X7LJIbEtmtf3x11niG9BuSIT3SVyfR/z0h+yKy7p/a6xnXdUC/E1OUMFnYIj4Po58InNGsJXUFJd9ASjY5dd2JXP4B1TJMcaMF338Z89Ko+2PVDYJvkXQMYelC9B5mkILc1zng4I4xwCczaV2AfJwfR/bUHvbw8M3vc9rQKuMtjPnv750UlEUl6l005bGX9JW4FQO5cVtEBh4fBZDaqpFNTlzhI=
